apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: ifani/udagram-api-user:v3
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: postgres.c5zbdc2f7mt1.us-east-1.rds.amazonaws.com
            - name: POSTGRES_DB
              value: postgres
            - name: AWS_BUCKET
              value: udagram-406042793940-prod
            - name: AWS_ACCESS_KEY_ID
              value: AKIAV5CQJK7KBGRANYHR
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_PROFILE
              value: default
            - name: JWT_SECRET
              value: testing
